// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepo(arg1) {
  return window['go']['main']['App']['AddRepo'](arg1);
}

export function CheckPRs() {
  return window['go']['main']['App']['CheckPRs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OnShutdown(arg1) {
  return window['go']['main']['App']['OnShutdown'](arg1);
}

export function Repos() {
  return window['go']['main']['App']['Repos']();
}

export function UpdateSchedule(arg1) {
  return window['go']['main']['App']['UpdateSchedule'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
