name: Build and Test

on:
  push:
    branches:
      - "*"

jobs:
  go-build-test:
    runs-on: ubuntu-latest  # The job will run on an Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This action checks out your repository

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'  # You can specify the Go version here


    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-

    - name: Install dependencies
      run: go mod tidy  

    - name: Run go tests
      run: go test -v ./...
      env:
        GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}

    - name: Install frontend dependencies
      run: npm ci

    - name: Run jest tests
      run: npm test
